Spawns:
  Red:
    X: 120
    Y: 120
    Z: 120
  Blue:
    X: 120
    Y: 120
    Z: 120
Minimum Players: 1
Staging Area:
    X: 120
    Y: 120
    Z: 120
Goals:
  Red:
    X: 120
    Y: 120
    Z: 120
  Blue:
    X: 120
    Y: 120
    Z: 120
Config:
  server: localhost
  table: bukkit
  database: bukkit
  user: root
  password: password
  interval: 5
  column_name: commands
  port: 3306
  singleuse: false
