name: CTF
description: Capture The Flag
main: me.jimbo.plugin.CTF
version: 0.7.0
author: teh_jombi
authors: [fireblast709]
commands:
   ctf:
       description: Manage Capture The Flag
   heavy:
       description: Respawn as a heavy.
       usage: /heavy
       permission: ctf.class.heavy
   soldier:
       description: Respawn as a soldier.
       usage: /soldier
       permission: ctf.class.soldier
   archer:
       description: Respawn as an archer.
       usage: /archer
       permission: ctf.class.archer
   medic:
       description: Respawn as a medic.
       usage: /medic
       permission: ctf.class.medic
   pyro:
       description: Respawn as a pyromaniac.
       usage: /pyro
       permission: ctf.class.pyro
   ninja:
       description: Respawn as a stealthy ninja.
       usage: /ninja
       permission: ctf.class.ninja
   engineer:
       description: Respawn as an engineer.
       usage: /engineer
       permission: ctf.class.engineer

