name: CTF
description: Capture The Flag
main: me.jimbo.plugin.CTF
version: 0.8.5
author: teh_jombi
authors: [fireblast709]
commands:
   ctf:
       description: Manage Capture The Flag
   heavy:
       description: Respawn as a heavy.
       permission: ctf.class.heavy
       permission-message: You need <permission> to use
   soldier:
       description: Respawn as a soldier.
       permission: ctf.class.soldier
       permission-message: You need <permission> to use
   archer:
       description: Respawn as an archer.
       permission: ctf.class.archer
       permission-message: You need <permission> to use
   medic:
       description: Respawn as a medic.
       permission: ctf.class.medic
       permission-message: You need <permission> to use
   pyro:
       description: Respawn as a pyromaniac.
       permission: ctf.class.pyro
       permission-message: You need <permission> to use
   ninja:
       description: Respawn as a stealthy ninja.
       permission: ctf.class.ninja
       permission-message: You need <permission> to use
   engineer:
       description: Respawn as an engineer.
       permission: ctf.class.engineer
       permission-message: You need <permission> to use
   firefly:
       description: Respawn as a firefly.
       permission: ctf.class.firefly
       permission-message: You need <permission> to use
   berserker:
       description: Respawn as a berserker.
       permission: ctf.class.berserker
       permission-message: You need <permission> to use
   martyr:
       description: Respawn as a martyr.
       permission: ctf.class.martyr
       permission-message: You need <permission> to use